name: CI-Packing
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Packing by PyInstaller Windows
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: ./
    - name: Ready for Packing
      run: |
        cd ./dist/windows
        mkdir ./OlivOS-Win
        cd ./OlivOS-Win
        cp -rf ../../../conf ./conf
        cp ../main.exe ./OlivOS.exe
    - uses: actions/upload-artifact@v2
      with:
        name: OlivOS-Win-pack
        path: ./dist/windows/OlivOS-Win
    - uses: actions/upload-artifact@v2
      with:
        name: OlivOS-Win-bin
        path: ./dist/windows/OlivOS-Win/OlivOS.exe
    - name: Ready for Packing
      run: |
        mkdir ./dist/windows/OlivOS-Win/lib
        curl -L https://github.com/Mrs4s/go-cqhttp/releases/latest/download/go-cqhttp_windows_amd64.exe -o ./dist/windows/OlivOS-Win/lib/go-cqhttp.exe
    - uses: actions/upload-artifact@v2
      with:
        name: OlivOS-Win-pack-with-lib
        path: ./dist/windows/OlivOS-Win
