name: CI-Packing
on:
  push:
    branches: [ pypipublish ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Pypi
        uses: remorses/pypi@v3
        with:
          setup_file: ./setup.py
          username: ${{ secrets.OWNERPYPIUSERNAME }}
          password: ${{ secrets.OWNERPYPIPASSWORD }}
