name: CI-Packing-win32
on:
  push:
    branches: [ 32bitDev ]
jobs:
  build:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v3.1.2
      with:
        python-version: 3.7.5
        cache: pip
        architecture: x86
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r .\requirements.txt
    - name: Run packing
      run: |
        python -m pyinstaller .\main.spec
