name: CI-Packing-win64
on:
  push:
    branches: [ main, dev ]
jobs:
  build_win64_release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Packing by PyInstaller Windows
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: ./
    - name: Ready for Packing
      run: |
        cd ./dist/windows
        mkdir ./OlivOS-Win
        cp ./main.exe ./OlivOS-Win/OlivOS.exe
    - name: Packing OlivOS-Win
      uses: actions/upload-artifact@v2
      with:
        name: OlivOS-Win
        path: ./dist/windows/OlivOS-Win
    - name: Ready for Packing
      run: |
        mkdir ./dist/windows/OlivOS-Win/lib
        curl -L https://github.com/Mrs4s/go-cqhttp/releases/latest/download/go-cqhttp_windows_amd64.exe -o ./dist/windows/OlivOS-Win/lib/go-cqhttp.exe
    - name: Packing OlivOS-Win-with-lib
      uses: actions/upload-artifact@v2
      with:
        name: OlivOS-Win-with-lib
        path: ./dist/windows/OlivOS-Win
  build_win64_debug:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Packing by PyInstaller Windows
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: ./
        spec: main_debug.spec
    - name: Ready for Packing
      run: |
        cd ./dist/windows
        mkdir ./OlivOS-Win
        cp ./main.exe ./OlivOS-Win/OlivOS_debug.exe
    - name: Packing OlivOS-Win
      uses: actions/upload-artifact@v2
      with:
        name: OlivOS-Win-debug
        path: ./dist/windows/OlivOS-Win
    - name: Ready for Packing
      run: |
        mkdir ./dist/windows/OlivOS-Win/lib
        curl -L https://github.com/Mrs4s/go-cqhttp/releases/latest/download/go-cqhttp_windows_amd64.exe -o ./dist/windows/OlivOS-Win/lib/go-cqhttp.exe
    - name: Packing OlivOS-Win-with-lib
      uses: actions/upload-artifact@v2
      with:
        name: OlivOS-Win-with-lib-debug
        path: ./dist/windows/OlivOS-Win
